# Generated by Django 6.0.7 on 2026-07-10 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_body', models.JSONField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
