# Generated by Django 5.2.16 on 2026-07-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='proxy.apikey'),
        ),
    ]
