# Generated by Django 5.2.16 on 2026-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_apikey_completion_tokens_apikey_estimated_cost_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='estimated_cost_usd',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='prompt_tokens',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
