# Generated by Django 5.2.16 on 2026-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_remove_apikey_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='provider',
            field=models.CharField(default='gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
