# Generated by Django 5.2.16 on 2026-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_requestlog_provider_alter_apikey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
